# Generated by Django 6.1.1 on 2026-09-29 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RefBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=100, unique=True, verbose_name="Код"),
                ),
                ("name", models.CharField(max_length=300, verbose_name="Наименование")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Описание"),
                ),
            ],
            options={
                "verbose_name": "Справочник",
                "verbose_name_plural": "Справочники",
                "ordering": ("id",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("code", ""), _negated=True),
                        name="refbook_code_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("name", ""), _negated=True),
                        name="refbook_name_not_empty",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RefBookVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=50, verbose_name="Версия")),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата начала действия"
                    ),
                ),
                (
                    "refbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="terminology.refbook",
                        verbose_name="Справочник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версия справочника",
                "verbose_name_plural": "Версии справочников",
                "ordering": ("refbook_id", "start_date", "id"),
            },
        ),
        migrations.CreateModel(
            name="RefBookElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100, verbose_name="Код элемента")),
                (
                    "value",
                    models.CharField(max_length=300, verbose_name="Значение элемента"),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="elements",
                        to="terminology.refbookversion",
                        verbose_name="Версия справочника",
                    ),
                ),
            ],
            options={
                "verbose_name": "Элемент справочника",
                "verbose_name_plural": "Элементы справочника",
                "ordering": ("code", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="refbookversion",
            constraint=models.UniqueConstraint(
                fields=("refbook", "version"), name="unique_refbook_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="refbookversion",
            constraint=models.UniqueConstraint(
                fields=("refbook", "start_date"), name="unique_refbook_start_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="refbookversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("version", ""), _negated=True),
                name="refbook_version_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="refbookelement",
            constraint=models.UniqueConstraint(
                fields=("version", "code"), name="unique_version_element_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="refbookelement",
            constraint=models.CheckConstraint(
                condition=models.Q(("code", ""), _negated=True),
                name="refelement_code_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="refbookelement",
            constraint=models.CheckConstraint(
                condition=models.Q(("value", ""), _negated=True),
                name="refelement_value_not_empty",
            ),
        ),
    ]
